name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust the version if necessary

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies you might need here

      - name: Fetch Comic and Update README
        run: |
          python update_readme.py || { echo 'Script failed'; exit 1; }

      - name: Configure Git
        run: |
          git config --global user.name 'ldomenichelli'
          git config --global user.email 'ldomenichelli2@gmail.com'  # Use your GitHub email

      - name: Pull Latest Changes
        run: git pull origin main  # Ensure you pull the latest changes before pushing

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Updated README with comic" || echo "No changes to commit"
          git push "https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git"

          
          # Push the changes
          git push "https://${ACTIONS_PAT}@github.com/ldomenichelli/ldomenichelli.git"
