name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests  # Ensure requests is installed

      - name: Fetch Comic and Update README
        run: python update_readme.py  # Run your script

      - name: Configure Git
        run: |
          git config --global user.name 'ldomenichelli'
          git config --global user.email 'ldomenichelli2@gmail.com'

      - name: Pull Latest Changes
        run: git pull origin main  # Ensure no conflicts when pushing

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git add README.md
          git commit -m "Updated README with comic" || echo "No changes to commit"
          git push "https://${ACTIONS_PAT}@github.com/${{ github.repository }}.git"

          
          # Push the changes
          git push "https://${ACTIONS_PAT}@github.com/ldomenichelli/ldomenichelli.git"
