name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify Python version explicitly

      - name: Create Virtual Environment and Install Dependencies
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate virtual environment
          python -m pip install --upgrade pip  # Upgrade pip
          python -m pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Verify Installation and Python Path
        run: |
          source venv/bin/activate  # Activate virtual environment
          python -m pip show requests  # Verifies requests is installed
          which python                # Check the Python path
          python --version            # Confirm Python version

      - name: Fetch Comic and Update README
        run: |
          source venv/bin/activate  # Activate virtual environment
          python update_readme.py || { echo 'Script failed'; exit 1; }

      - name: Configure Git
        run: |
          git config --global user.name 'ldomenichelli'
          git config --global user.email 'ldomenichelli2@gmail.com'

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git add README.md
          git commit -m "Updated README with comic" || echo "No changes to commit"
          git push "https://${ACTIONS_PAT}@github.com/${{ github.repository }}.git"

